# Database
db.url=jdbc:mysql://localhost:3306/new_db?rewriteBatchedStatements=true&allowMultiQueries=true&allowLoadLocalInfile=true
db.user=itc
db.password=itc

# RabbitMQ
rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.user=guest
rabbitmq.pass=guest
rabbitmq.queue=record.queue
